export const MAJOR_SELECTED = "MAJOR_SELECTED";
export const SUBJECT_SELECTED = "SUBJECT_SELECTED";
export const SUBJECT_DESELECTED = "SUBJECT_DESELECTED";
export const RESET_SUBJECT_SELECTED = "RESET_SUBJECT_SELECTED";
